# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LR8rWZzhJZhAFeiVyFd8Utmo7Whf09n9
"""

# app.py
import streamlit as st
import json
from utils.search_post import search_post

# Load Reddit data
with open("data/reddit_data.json", "r") as f:
    reddit_posts = json.load(f)

st.title("SoleFacts: Search Running Shoe Feedback")

query = st.text_input("What do you want to know?")

if query:
    results = search_post(query, reddit_posts)
    for r in results:
        st.markdown(f"- **{r['model']}**: {r['text']}")